// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// createFile
void createFile(arma::uword nrow, arma::uword ncol, std::string fileName);
RcppExport SEXP _rmada_createFile(SEXP nrowSEXP, SEXP ncolSEXP, SEXP fileNameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    createFile(nrow, ncol, fileName);
    return R_NilValue;
END_RCPP
}
// mapFile
SEXP mapFile(std::string fileName);
RcppExport SEXP _rmada_mapFile(SEXP fileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    rcpp_result_gen = Rcpp::wrap(mapFile(fileName));
    return rcpp_result_gen;
END_RCPP
}
// createMat
SEXP createMat(SEXP memory, arma::uword nrow, arma::uword ncol);
RcppExport SEXP _rmada_createMat(SEXP memorySEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type memory(memorySEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(createMat(memory, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// nRows
arma::uword nRows(SEXP x);
RcppExport SEXP _rmada_nRows(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(nRows(x));
    return rcpp_result_gen;
END_RCPP
}
// nCols
arma::uword nCols(SEXP x);
RcppExport SEXP _rmada_nCols(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(nCols(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rmada_createFile", (DL_FUNC) &_rmada_createFile, 3},
    {"_rmada_mapFile", (DL_FUNC) &_rmada_mapFile, 1},
    {"_rmada_createMat", (DL_FUNC) &_rmada_createMat, 3},
    {"_rmada_nRows", (DL_FUNC) &_rmada_nRows, 1},
    {"_rmada_nCols", (DL_FUNC) &_rmada_nCols, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rmada(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
