# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_mem <- function(name, length, data_type, mem_type) {
    .Call(`_rmada_init_mem`, name, length, data_type, mem_type)
}

