# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mat_init <- function(mem, n_rows, n_cols, data_type) {
    .Call(`_rmada_mat_init`, mem, n_rows, n_cols, data_type)
}

n_rows <- function(x) {
    .Call(`_rmada_n_rows`, x)
}

n_cols <- function(x) {
    .Call(`_rmada_n_cols`, x)
}

mem_init <- function(name, length, data_type, mem_type) {
    .Call(`_rmada_mem_init`, name, length, data_type, mem_type)
}

mem_attach <- function(mem) {
    invisible(.Call(`_rmada_mem_attach`, mem))
}

mem_detach <- function(mem) {
    invisible(.Call(`_rmada_mem_detach`, mem))
}

is_mem_attached <- function(mem) {
    .Call(`_rmada_is_mem_attached`, mem)
}

get_mem_address <- function(mem, data_type) {
    .Call(`_rmada_get_mem_address`, mem, data_type)
}

get_mem_length <- function(mem, data_type) {
    .Call(`_rmada_get_mem_length`, mem, data_type)
}

get_mem_id <- function(mem) {
    .Call(`_rmada_get_mem_id`, mem)
}

mem_remove <- function(mem) {
    invisible(.Call(`_rmada_mem_remove`, mem))
}

mem_resize <- function(mem, length, data_type) {
    invisible(.Call(`_rmada_mem_resize`, mem, length, data_type))
}

